CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Utilisateurs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(255) NOT NULL,
    "Prenom" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "MotDePasse" character varying(255) NOT NULL,
    "DateDeNaissance" timestamp with time zone NOT NULL,
    "OnCreate" timestamp with time zone NOT NULL,
    "OnUpdate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Utilisateurs" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241225192232_InitialCreate', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Utilisateurs" ADD "EstAdmin" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "Espaces" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(255) NOT NULL,
    "Adresse" character varying(255) NOT NULL,
    "Ville" character varying(255) NOT NULL,
    "CodePostal" character varying(255) NOT NULL,
    "Capacite" integer NOT NULL,
    "OnCreate" timestamp with time zone NOT NULL,
    "OnUpdate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Espaces" PRIMARY KEY ("Id")
);

CREATE TABLE "TypePlaces" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" character varying(50) NOT NULL,
    CONSTRAINT "PK_TypePlaces" PRIMARY KEY ("Id")
);

CREATE TABLE "Evenements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EspaceId" integer NOT NULL,
    "Nom" character varying(255) NOT NULL,
    "Description" text NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Heure" interval NOT NULL,
    "Lieu" character varying(255) NOT NULL,
    "OnCreate" timestamp with time zone NOT NULL,
    "OnUpdate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Evenements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Evenements_Espaces_EspaceId" FOREIGN KEY ("EspaceId") REFERENCES "Espaces" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EvenementTypePlaces" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EvenementId" integer NOT NULL,
    "TypePlaceId" integer NOT NULL,
    "NombreDePlaces" integer NOT NULL,
    "Prix" numeric(10,2) NOT NULL,
    "OnCreate" timestamp with time zone NOT NULL,
    "OnUpdate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EvenementTypePlaces" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvenementTypePlaces_Evenements_EvenementId" FOREIGN KEY ("EvenementId") REFERENCES "Evenements" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EvenementTypePlaces_TypePlaces_TypePlaceId" FOREIGN KEY ("TypePlaceId") REFERENCES "TypePlaces" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PlaceVendues" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EvenementId" integer NOT NULL,
    "TypePlaceId" integer NOT NULL,
    "UtilisateurId" integer NOT NULL,
    "NombreDePlaces" integer NOT NULL,
    "Prix" numeric(10,2) NOT NULL,
    "OnCreate" timestamp with time zone NOT NULL,
    "OnUpdate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PlaceVendues" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PlaceVendues_Evenements_EvenementId" FOREIGN KEY ("EvenementId") REFERENCES "Evenements" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlaceVendues_TypePlaces_TypePlaceId" FOREIGN KEY ("TypePlaceId") REFERENCES "TypePlaces" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PlaceVendues_Utilisateurs_UtilisateurId" FOREIGN KEY ("UtilisateurId") REFERENCES "Utilisateurs" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Evenements_EspaceId" ON "Evenements" ("EspaceId");

CREATE INDEX "IX_EvenementTypePlaces_EvenementId" ON "EvenementTypePlaces" ("EvenementId");

CREATE INDEX "IX_EvenementTypePlaces_TypePlaceId" ON "EvenementTypePlaces" ("TypePlaceId");

CREATE INDEX "IX_PlaceVendues_EvenementId" ON "PlaceVendues" ("EvenementId");

CREATE INDEX "IX_PlaceVendues_TypePlaceId" ON "PlaceVendues" ("TypePlaceId");

CREATE INDEX "IX_PlaceVendues_UtilisateurId" ON "PlaceVendues" ("UtilisateurId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241228062943_UpdateModels', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Espaces" ADD "Largeur" integer NOT NULL DEFAULT 0;

ALTER TABLE "Espaces" ADD "Longueur" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241228123820_InitialCreate1', '8.0.0');

COMMIT;

